using System.Globalization;
namespace PSiptv.Services;

public static class LanguageService
{
    private static readonly CultureInfo systemCulture = CultureInfo.CurrentUICulture;
    public static string DisplayName => Preferences.Default.Get("language", "system") switch { "en" => "English", "pt" => "Português", _ => "Do sistema" };
    public static void Apply(string? language = null)
    {
        if (language is not null) Preferences.Default.Set("language", language);
        var selected = Preferences.Default.Get("language", "system");
        var culture = selected switch { "en" => new CultureInfo("en-GB"), "pt" => new CultureInfo("pt-PT"), _ => systemCulture };
        CultureInfo.DefaultThreadCurrentCulture = culture; CultureInfo.DefaultThreadCurrentUICulture = culture;
        CultureInfo.CurrentCulture = culture; CultureInfo.CurrentUICulture = culture;
    }
    public static async Task<string> ActionSheetAsync(Page page, string title, string? cancel, string? destruction, params string[] buttons)
    {
        var labels = buttons.Select(Text).ToArray();
        var answer = await page.DisplayActionSheetAsync(Text(title), cancel is null ? null : Text(cancel), destruction is null ? null : Text(destruction), labels);
        var index = Array.IndexOf(labels, answer); return index < 0 ? answer : buttons[index];
    }
    public static Task AlertAsync(Page page, string title, string message, string cancel = "OK") =>
        page.DisplayAlertAsync(Text(title), Text(message), Text(cancel));
    public static Task<bool> ConfirmAsync(Page page, string title, string message, string accept, string cancel) =>
        page.DisplayAlertAsync(Text(title), Text(message), Text(accept), Text(cancel));
    public static string Format(string template, params object?[] values) =>
        string.Format(CultureInfo.CurrentCulture, Text(template), values);
    public static string Text(string text)
    {
        if (CultureInfo.CurrentUICulture.TwoLetterISOLanguageName != "en") return text;
        var suffix = text.EndsWith("  ›") ? "  ›" : "";
        var key = suffix.Length > 0 ? text[..^3] : text;
        if (translations.TryGetValue(key, out var value)) return value + suffix;
        var patterns = new (string Pattern, string Replacement)[]
        {
            (@"^(\d+) conteúdos · Selecione para reproduzir\.$", "$1 items · Select to play."),
            (@"^Todas as categorias \((\d+)\)$", "All categories ($1)"),
            (@"^(\d+) episódios · Organizados por temporada$", "$1 episodes · Organized by season"),
            (@"^(\d+) programas · Horário local do dispositivo$", "$1 programmes · Device local time"),
            (@"^(\d+) canais · Selecione um canal para reproduzir\.$", "$1 channels · Select a channel to play."),
            (@"^(\d+) s entre episódios$", "$1 seconds between episodes"),
            (@"^(\d+) segundos de cache de rede$", "$1 seconds of network cache"),
            (@"^(.+) s entre episódios$", "$1 seconds between episodes"),
            (@"^(.+) segundos de cache de rede$", "$1 seconds of network cache"),
            (@"^Versão: (.+)$", "Version: $1"),
            (@"^(\d+) conteúdos$", "$1 items"),
            (@"^(.+) · (\d+) conteúdos$", "$1 · $2 items"),
            (@"^(\d+) canais favoritos · Selecione para reproduzir\.$", "$1 favourite channels · Select to play."),
            (@"^(\d+) canais · Escolha um canal para consultar a programação\.$", "$1 channels · Choose a channel to view its schedule."),
            (@"^Foram encontrados (\d+) canais\.$", "$1 channels were found."),
            (@"^Foram encontrados (\d+) programas\.$", "$1 programmes were found."),
            (@"^«(.+)» respondeu HTTP (.+)$", "‘$1’ responded with HTTP $2"),
            (@"^(\d+) downloads · (.+) offline$", "$1 downloads · $2 offline"),
            (@"^Aguarde (\d+) segundos antes de tentar novamente\.$", "Wait $1 seconds before trying again."),
            (@"^Próximo episódio em (\d+) s · (.+)$", "Next episode in $1 s · $2"),
            (@"^([0-9.,]+) Mbps · transmissão$", "$1 Mbps · stream"),
            (@"^Eliminar «(.+)» deste dispositivo\?$", "Delete ‘$1’ from this device?"),
            (@"^Remover «(.+)»\?$", "Remove ‘$1’?"),
            (@"^Proporção do ecrã: (.+)$", "Screen aspect ratio: $1")
            ,(@"^Episódio (.+)$", "Episode $1")
            ,(@"^Temporada (.+)$", "Season $1")
            ,(@"^Canal (\d+)$", "Channel $1")
            ,(@"^(.+) · Protegida com PIN$", "$1 · PIN protected")
            ,(@"^(.+) · Sem PIN$", "$1 · No PIN")
        };
        foreach (var (pattern, replacement) in patterns) if (System.Text.RegularExpressions.Regex.IsMatch(key, pattern)) return System.Text.RegularExpressions.Regex.Replace(key, pattern, replacement) + suffix;
        return key + suffix;
    }
    private static readonly Dictionary<string, string> translations = new()
    {
        ["Diagnóstico de fontes"] = "Source diagnostics", ["Diagnosticar fonte"] = "Diagnose source",
        ["Downloads offline"] = "Offline downloads", ["Descarregar"] = "Download", ["Ver download"] = "View download",
        ["Abrir pasta dos downloads"] = "Open downloads folder", ["Pasta dos downloads"] = "Downloads folder",
        ["Pause os downloads em curso antes de alterar a pasta."] = "Pause active downloads before changing the folder.",
        ["A pasta escolhida já contém um ficheiro com o mesmo nome de um download."] = "The selected folder already contains a file with the same name as a download.",
        ["Controlo Chromecast"] = "Chromecast controls", ["A obter estado do Chromecast…"] = "Getting Chromecast status…",
        ["Legendas externas"] = "External subtitles", ["Escolher ficheiro SRT/VTT"] = "Choose SRT/VTT file",
        ["Escolher legendas SRT ou WebVTT"] = "Choose SRT or WebVTT subtitles",
        ["Adicionar legendas por URL"] = "Add subtitles by URL", ["Desligar legendas externas"] = "Turn off external subtitles",
        ["Ligar legendas externas"] = "Turn on external subtitles", ["Legendas externas ativas."] = "External subtitles enabled.",
        ["Legendas externas desligadas."] = "External subtitles disabled.", ["Carregar"] = "Load",
        ["Endereço HTTP ou HTTPS de um ficheiro SRT ou WebVTT."] = "HTTP or HTTPS address of an SRT or WebVTT file.",
        ["Escolha um ficheiro de legendas .srt ou .vtt."] = "Choose an .srt or .vtt subtitle file.",
        ["O ficheiro de legendas está vazio."] = "The subtitle file is empty.",
        ["Não foram encontradas legendas SRT ou WebVTT válidas."] = "No valid SRT or WebVTT subtitles were found.",
        ["O ficheiro de legendas excede o limite de 5 MB."] = "The subtitle file exceeds the 5 MB limit.",
        ["A reproduzir no recetor"] = "Playing on receiver", ["Volume do Chromecast"] = "Chromecast volume",
        ["Anterior"] = "Previous", ["Seguinte"] = "Next", ["Silenciar"] = "Mute", ["Ativar som"] = "Unmute",
        ["Parar transmissão"] = "Stop casting", ["Desligar Chromecast"] = "Disconnect Chromecast",
        ["O controlo Chromecast avançado está disponível no Android."] = "Advanced Chromecast controls are available on Android.",
        ["O Chromecast já não está ligado."] = "The Chromecast is no longer connected.",
        ["Conteúdo no Chromecast"] = "Content on Chromecast",
        ["Transmissão em direto ou duração indisponível"] = "Live stream or duration unavailable",
        ["Ligado a {0}"] = "Connected to {0}", ["Volume {0}%"] = "Volume {0}%",
        ["Reproduzir offline"] = "Play offline", ["Pausar download"] = "Pause download", ["Retomar download"] = "Resume download",
        ["A carregar downloads…"] = "Loading downloads…", ["Não existem downloads neste perfil."] = "There are no downloads in this profile.",
        ["Eliminar download"] = "Delete download", ["Eliminar o download e o respetivo ficheiro?"] = "Delete the download and its file?",
        ["Em fila"] = "Queued", ["A descarregar"] = "Downloading", ["Em pausa"] = "Paused", ["Disponível offline"] = "Available offline",
        ["O episódio foi adicionado aos downloads."] = "The episode was added to downloads.",
        ["Este conteúdo não tem um endereço VOD descarregável."] = "This item does not have a downloadable VOD address.",
        ["O download foi interrompido. Pode retomá-lo."] = "The download was interrupted. You can resume it.",
        ["O ficheiro descarregado já não existe."] = "The downloaded file no longer exists.",
        ["O ficheiro offline ainda não está disponível."] = "The offline file is not available yet.",
        ["Este VOD usa HLS segmentado e ainda não pode ser descarregado para reprodução offline."] = "This VOD uses segmented HLS and cannot yet be downloaded for offline playback.",
        ["O endereço VOD devolveu uma página HTML em vez de vídeo."] = "The VOD address returned an HTML page instead of video.",
        ["Estado da fonte"] = "Source status", ["Fonte selecionada"] = "Selected source",
        ["Executar diagnóstico"] = "Run diagnostics", ["Copiar relatório"] = "Copy report",
        ["Pronto para executar o diagnóstico."] = "Ready to run diagnostics.", ["A executar os testes…"] = "Running tests…",
        ["Abra uma lista para testar a respetiva fonte."] = "Open a playlist to test its source.",
        ["Verifica a ligação, o catálogo, o guia EPG e uma stream de amostra sem iniciar a reprodução."] = "Checks the connection, catalogue, EPG and a sample stream without starting playback.",
        ["Fonte operacional. Todos os testes passaram."] = "The source is operational. All tests passed.",
        ["Fonte disponível, mas existem avisos a rever."] = "The source is available, but there are warnings to review.",
        ["Foram detetados problemas na fonte."] = "Problems were detected with the source.",
        ["Relatório copiado sem credenciais nem tokens."] = "Report copied without credentials or tokens.",
        ["Ligação e autenticação"] = "Connection and authentication", ["Catálogo de canais"] = "Channel catalogue",
        ["Guia EPG"] = "EPG guide", ["Stream de amostra"] = "Sample stream",
        ["A fonte aceitou a ligação e as credenciais."] = "The source accepted the connection and credentials.",
        ["Ignorado porque a ligação falhou."] = "Skipped because the connection failed.",
        ["Não existe uma fonte EPG configurada para este fornecedor."] = "No EPG source is configured for this provider.",
        ["O guia respondeu, mas não contém programas válidos."] = "The guide responded but contains no valid programmes.",
        ["Não existe um canal disponível para testar."] = "There is no channel available to test.",
        ["Os canais não contêm um endereço de reprodução testável."] = "The channels contain no testable playback address.",
        ["O endereço da stream devolveu uma página HTML em vez de vídeo."] = "The stream address returned an HTML page instead of video.",
        ["O teste excedeu o tempo limite."] = "The test timed out.",
        ["Não foi possível estabelecer ligação ao servidor."] = "Could not connect to the server.",
        ["O teste falhou sem detalhes adicionais."] = "The test failed without further details.",
        ["Automático"] = "Automatic", ["Padrão"] = "Default", ["XMLTV personalizado"] = "Custom XMLTV", ["Ainda não atualizado"] = "Not updated yet", ["24 horas"] = "24 hours", ["12 horas"] = "12 hours",
        ["{0} canais favoritos · Selecione para reproduzir."] = "{0} favourite channels · Select to play.", ["{0} canais · Escolha um canal para consultar a programação."] = "{0} channels · Choose a channel to view its schedule.",
        ["{0} conteúdos · Selecione para reproduzir."] = "{0} items · Select to play.", ["{0} canais · Selecione um canal para reproduzir."] = "{0} channels · Select a channel to play.",
        ["{0} · {1} conteúdos"] = "{0} · {1} items", ["{0} episódios · Organizados por temporada"] = "{0} episodes · Organized by season",
        ["{0} programas · Horário local do dispositivo"] = "{0} programmes · Device local time", ["{0} favoritos · {1}"] = "{0} favourites · {1}",
        ["Aguarde {0} segundos antes de tentar novamente."] = "Wait {0} seconds before trying again.", ["{0:F2} Mbps · transmissão"] = "{0:F2} Mbps · stream",
        ["Próximo episódio em {0} s · {1}"] = "Next episode in {0} s · {1}", ["Versão: {0}"] = "Version: {0}",
        ["O formato aplica-se aos canais Xtream. Os endereços M3U são preservados."] = "The format applies to Xtream live channels. M3U URLs are preserved.",
        ["Atualizar conteúdo"] = "Refresh content", ["Trocar playlist"] = "Switch playlist", ["Pesquisar canais, favoritos ou séries"] = "Search channels, favorites or series",
        ["Início"] = "Home", ["Olá, {0}"] = "Hello, {0}", ["Escolhas para si"] = "Picked for you", ["Atualizar início"] = "Refresh home",
        ["Continuar a ver"] = "Continue watching", ["Retomar em {0}"] = "Resume at {0}", ["Canais recentes"] = "Recent channels", ["Visto em {0}"] = "Watched {0}",
        ["A começar"] = "Starting soon", ["Começa às {0}"] = "Starts at {0}", ["Gravações recentes"] = "Recent recordings",
        ["Abra uma lista para preparar a sua página inicial."] = "Open a playlist to prepare your home page.", ["A preparar a sua página inicial…"] = "Preparing your home page…",
        ["Não foi possível preparar a página inicial."] = "The home page could not be prepared.", ["A sua página inicial ainda está vazia."] = "Your home page is still empty.",
        ["Veja um canal, adicione favoritos ou agende uma gravação para começar."] = "Watch a channel, add favourites or schedule a recording to get started.",
        ["A preparar a página inicial…"] = "Preparing the home page…", ["Sugestões personalizadas a partir da sua atividade."] = "Personalized suggestions based on your activity.",
        ["A página inicial foi aberta com os dados disponíveis."] = "The home page was opened with the available data.", ["A página principal já não está disponível."] = "The main page is no longer available.",
        ["Mais opções"] = "More options", ["Bloquear"] = "Lock", ["Ordem do fornecedor"] = "Provider order", ["Nome A–Z"] = "Name A–Z", ["Nome Z–A"] = "Name Z–A",
        ["Tipo de conteúdo"] = "Content type", ["Ordenar por"] = "Sort by",
        ["Ligado"] = "Enabled", ["Desligado"] = "Disabled", ["Livre"] = "Unrestricted", ["Protegida 🔒"] = "Protected 🔒", ["Visível"] = "Visible", ["Oculta"] = "Hidden",
        ["Cabeçalho enviado ao fornecedor e ao leitor integrado Android."] = "Header sent to the provider and the integrated Android player.",
        ["Endereço XMLTV. Deixe vazio para usar a fonte do fornecedor."] = "XMLTV URL. Leave blank to use the provider source.",
        ["Abra uma lista primeiro."] = "Open a playlist first.", ["PIN incorreto. Tente novamente."] = "Incorrect PIN. Try again.",
        ["Toque em Livre para exigir o PIN ao reproduzir conteúdos dessa categoria."] = "Tap Unrestricted to require the PIN when playing content in that category.",
        ["As alterações são guardadas nesta lista. Use as setas para ordenar."] = "Changes are saved for this playlist. Use the arrows to reorder.",
        ["Do sistema acompanha automaticamente a aparência do dispositivo."] = "System automatically follows your device appearance.",
        ["As opções do leitor aplicam-se ao abrir o próximo vídeo. Hardware depende dos codecs do dispositivo. A velocidade indica os dados recebidos pela transmissão."] = "Player options apply when opening the next video. Hardware decoding depends on device codecs. Speed shows the stream data received.",
        ["As opções do leitor aplicam-se ao abrir o próximo vídeo. Hardware depende dos codecs do dispositivo. O Timeshift usa armazenamento temporário e a disponibilidade de pausa ou recuo depende do stream."] = "Player options apply when opening the next video. Hardware decoding depends on device codecs. Timeshift uses temporary storage, and pause or rewind availability depends on the stream.",
        ["As listas protegidas continuam a pedir PIN ou biometria. Para ativar a biometria numa lista, confirme primeiro o PIN no ecrã de desbloqueio."] = "Protected playlists still require a PIN or biometrics. To enable biometrics, first confirm the PIN on the unlock screen.",
        ["As credenciais são guardadas no armazenamento seguro do dispositivo. O PIN volta a ser pedido depois de bloquear ou sair da aplicação."] = "Credentials are kept in secure device storage. The PIN is required again after locking or leaving the app.",
        ["Abre canais, filmes e episódios num leitor instalado. Pode também usar «Abrir com leitor externo» durante a reprodução. O endereço do vídeo será enviado ao leitor escolhido."] = "Opens channels, movies and episodes in an installed player. You can also choose Open with external player during playback. The video URL will be sent to that player.",
        ["Ative após confirmar o PIN. Qualquer biometria registada neste dispositivo poderá abrir esta lista."] = "Enable after confirming the PIN. Any biometrics enrolled on this device can open this playlist.",
        ["Lista bloqueada. Escolha «Abrir lista» para voltar a entrar."] = "Playlist locked. Choose Open playlist to sign in again.",
        ["A sua televisão começa aqui."] = "Your television starts here.", ["Ligue a sua conta e organize os conteúdos num só lugar."] = "Connect your account and organize your content in one place.",
        ["Ligação"] = "Connection", ["Endereço do servidor ou da lista"] = "Server or playlist URL", ["Nome de utilizador"] = "Username", ["Ex.: TV de casa"] = "For example: Home TV",
        ["PIN de acesso"] = "Access PIN", ["Opcional. Será pedido ao abrir a lista."] = "Optional. Required when opening the playlist.", ["4 a 8 algarismos (opcional)"] = "4 to 8 digits (optional)",
        ["Confirmar novo PIN"] = "Confirm new PIN", ["Testar ligação e guardar"] = "Test connection and save", ["Pesquisar conteúdo"] = "Search content",
        ["Configurações"] = "Settings", ["Configurações Gerais"] = "General settings", ["Configurações do Player"] = "Player settings",
        ["Imagem em Imagem"] = "Picture in picture", ["Formato de Transmissão"] = "Stream format", ["Episódio Auto Play"] = "Episode autoplay",
        ["Segundos para Auto Play"] = "Autoplay delay", ["Limpar Cache Automaticamente"] = "Clear cache automatically", ["Limpar cache agora"] = "Clear cache now",
        ["Atualização das listas"] = "Playlist updates", ["Manual"] = "Manual", ["Ao arrancar"] = "On startup",
        ["Diariamente"] = "Daily", ["Semanalmente"] = "Weekly", ["Apenas por Wi-Fi"] = "Wi-Fi only",
        ["Atualizar em segundo plano"] = "Update in the background", ["Última atualização automática"] = "Last automatic update",
        ["Ainda não atualizado automaticamente"] = "Not updated automatically yet",
        ["Manual é a opção predefinida e mantém o botão ↻. Em segundo plano, o sistema executa a atualização quando houver oportunidade; no Android, a tarefa fica agendada mesmo depois de sair da aplicação."] = "Manual is the default and keeps the ↻ button. In the background, the system runs the update when possible; on Android, the task remains scheduled after leaving the app.",
        ["Lista atualizada · +{0} / −{1} canais"] = "Playlist updated · +{0} / −{1} channels",
        ["Ao ativar, o cache do guia e das imagens é limpo imediatamente e em cada arranque. Desativar preserva o cache existente."] = "When enabled, guide and image caches are cleared immediately and on every startup. Disabling preserves the existing cache.",
        ["Histórico de Visualização"] = "Watch history", ["Faixa de Legendas"] = "Subtitle track", ["Formato de Hora"] = "Clock format", ["Ordenar Por"] = "Sort by",
        ["Agente do Utilizador"] = "User agent", ["Idioma"] = "Language", ["Fonte EPG"] = "EPG source", ["Controlo Parental"] = "Parental controls",
        ["Ligar / Desligar"] = "Enable / Disable", ["Alterar código PIN"] = "Change PIN", ["Categorias protegidas"] = "Protected categories",
        ["Personalizar Categorias"] = "Customize categories", ["Reordenar e mostrar / ocultar categorias"] = "Reorder and show / hide categories",
        ["Adicionar / editar categorias personalizadas"] = "Add / edit custom categories", ["Descodificador do Player"] = "Player decoder",
        ["Limite de Tamanho de Buffer"] = "Network buffer size", ["Mostrar Velocidade de Rede"] = "Show network speed",
        ["Timeshift nos canais em direto"] = "Timeshift on live channels", ["Janela máxima de Timeshift"] = "Maximum Timeshift window",
        ["5 minutos"] = "5 minutes", ["15 minutos"] = "15 minutes", ["60 minutos"] = "60 minutes", ["120 minutos"] = "120 minutes",
        ["DIRETO"] = "LIVE", ["Em direto"] = "Live", ["A regressar ao direto…"] = "Returning to live…",
        ["Recuar 30 segundos"] = "Rewind 30 seconds", ["Avançar 30 segundos"] = "Forward 30 seconds", ["Voltar ao direto"] = "Return to live",
        ["Timeshift não está disponível neste stream."] = "Timeshift is not available on this stream.",
        ["O fornecedor não permite recuar neste stream."] = "The provider does not allow seeking back on this stream.",
        ["Janela máxima atingida. A reprodução foi retomada."] = "Maximum Timeshift window reached. Playback was resumed.",
        ["Idioma de áudio preferido"] = "Preferred audio language", ["Modo das legendas"] = "Subtitle mode",
        ["Idioma de legendas preferido"] = "Preferred subtitle language", ["Memorizar faixas escolhidas"] = "Remember selected tracks",
        ["Atraso do áudio"] = "Audio delay", ["Atraso das legendas"] = "Subtitle delay",
        ["Desligadas"] = "Off", ["Quando o áudio for diferente"] = "When audio language differs",
        ["Sempre que disponíveis"] = "Whenever available", ["Português"] = "Portuguese",
        ["Escolher faixa de áudio"] = "Choose audio track", ["Faixa de áudio"] = "Audio track", ["Áudio"] = "Audio",
        ["Este vídeo não contém faixas de áudio selecionáveis."] = "This video has no selectable audio tracks.",
        ["OpenSL ES (saída de áudio)"] = "OpenSL ES (audio output)", ["OpenGL (saída de vídeo)"] = "OpenGL (video output)",
        ["Sobre"] = "About", ["Política de Privacidade"] = "Privacy policy", ["Termos de Uso"] = "Terms of use",
        ["TV ao Vivo"] = "Live TV", ["Filmes"] = "Movies", ["Séries"] = "Series", ["Filmes e Séries"] = "Movies & Series", ["Filmes/Séries"] = "Movies/Series", ["Browser"] = "Browser", ["Perfil"] = "Profile", ["Opções"] = "Options", ["Favoritos"] = "Favorites", ["A carregar favoritos…"] = "Loading favorites…", ["A atualizar favoritos em segundo plano…"] = "Updating favorites in the background…", ["A atualizar canais em segundo plano…"] = "Updating channels in the background…",
        ["Multiview"] = "Multiview", ["Abrir Multiview"] = "Open Multiview", ["Adicionar canal"] = "Add channel",
        ["Escolher canal"] = "Choose channel", ["Trocar canal"] = "Change channel", ["Remover canal"] = "Remove channel",
        ["Ativar áudio deste canal"] = "Enable this channel's audio", ["Áudio ativo"] = "Audio enabled",
        ["Selecione um painel para ouvir o respetivo canal."] = "Select a tile to hear its channel.",
        ["Áudio ativo · {0}"] = "Audio enabled · {0}", ["Toque para escolher"] = "Tap to choose",
        ["O Multiview permite até quatro canais em simultâneo."] = "Multiview supports up to four simultaneous channels.",
        ["Não existem outros canais disponíveis nesta categoria."] = "There are no other channels available in this category.",
        ["Não existem canais disponíveis nesta categoria."] = "There are no channels available in this category.",
        ["Não foi possível reproduzir este canal."] = "This channel could not be played.",
        ["Perfis de utilizador"] = "User profiles", ["Quem está a ver?"] = "Who's watching?",
        ["Editar perfil"] = "Edit profile", ["Escolher ícone"] = "Choose icon", ["Continuar"] = "Continue",
        ["Cada perfil tem favoritos e histórico próprios. As listas e os catálogos são partilhados."] = "Each profile has its own favourites and history. Playlists and catalogues are shared.",
        ["+ Adicionar perfil"] = "+ Add profile", ["Adicionar perfil"] = "Add profile", ["Nome do perfil"] = "Profile name",
        ["Perfil ativo"] = "Active profile", ["Usar este perfil"] = "Use this profile", ["Eliminar perfil"] = "Delete profile",
        ["Eliminar o perfil «{0}» e os seus favoritos e histórico?"] = "Delete profile “{0}” and its favourites and history?",
        ["Eliminar o perfil «{0}» e todos os seus dados e gravações?"] = "Delete profile “{0}” and all its data and recordings?",
        ["O nome do perfil deve ter entre 1 e 30 caracteres."] = "The profile name must be between 1 and 30 characters.",
        ["Pode criar até 8 perfis."] = "You can create up to 8 profiles.", ["Já existe um perfil com esse nome."] = "A profile with that name already exists.",
        ["O perfil selecionado já não existe."] = "The selected profile no longer exists.", ["O perfil Principal não pode ser eliminado."] = "The Main profile cannot be deleted.",
        ["Mude de perfil antes de o eliminar."] = "Switch profiles before deleting it.",
        ["Sincronização e cópia de segurança"] = "Sync and backup", ["Exporte e importe os seus dados"] = "Export and import your data",
        ["Criar cópia"] = "Create backup", ["Restaurar e sincronizar"] = "Restore and sync",
        ["Inclui listas, perfis, favoritos, histórico e configurações. Guarde o ficheiro no serviço cloud ou dispositivo que preferir."] = "Includes playlists, profiles, favourites, history and settings. Save the file to your preferred cloud service or device.",
        ["O ficheiro não é encriptado. Guarde-o num local privado."] = "The file is not encrypted. Keep it in a private location.",
        ["Os dados da cópia são unidos aos deste dispositivo. As listas e perfis que já existem são atualizados."] = "Backup data is merged with the data on this device. Existing playlists and profiles are updated.",
        ["Criar e partilhar cópia"] = "Create and share backup", ["Escolher cópia para restaurar"] = "Choose backup to restore",
        ["A criar cópia…"] = "Creating backup…", ["Guardar ou partilhar cópia PSiptv"] = "Save or share PSiptv backup",
        ["Cópia criada. Confirme que guardou o ficheiro num local seguro."] = "Backup created. Make sure you saved the file in a safe place.",
        ["Escolher cópia PSiptv"] = "Choose PSiptv backup", ["Restaurar cópia"] = "Restore backup",
        ["Unir os dados desta cópia aos dados atuais?"] = "Merge this backup with the current data?", ["Restaurar"] = "Restore",
        ["A restaurar cópia…"] = "Restoring backup…", ["Cópia restaurada"] = "Backup restored",
        ["Os dados foram sincronizados. Abra uma lista para continuar."] = "Data was synced. Open a playlist to continue.",
        ["A cópia de segurança excede o limite de 50 MB."] = "The backup exceeds the 50 MB limit.",
        ["A cópia de segurança está vazia."] = "The backup is empty.", ["Não foi possível ler a cópia de segurança."] = "The backup could not be read.",
        ["Esta versão da cópia de segurança não é suportada."] = "This backup version is not supported.",
        ["O ficheiro não é uma cópia de segurança PSiptv válida."] = "The file is not a valid PSiptv backup.",
        ["Fontes do browser"] = "Browser sources", ["Escolher fonte"] = "Choose source", ["Adicionar fonte"] = "Add source", ["Editar fonte"] = "Edit source",
        ["Guia TV"] = "TV guide", ["Pesquisar"] = "Search", ["Todas as categorias"] = "All categories", ["Nenhuma lista aberta"] = "No playlist open",
        ["Lembretes de programas"] = "Programme reminders", ["Lembrete de programa"] = "Programme reminder",
        ["Criar lembrete"] = "Create reminder", ["Remover lembrete"] = "Remove reminder",
        ["Lembrete criado"] = "Reminder created", ["Lembrete removido"] = "Reminder removed",
        ["A carregar lembretes…"] = "Loading reminders…", ["Não existem lembretes futuros neste perfil."] = "There are no future reminders in this profile.",
        ["{0} lembretes futuros · Perfil {1}"] = "{0} future reminders · Profile {1}",
        ["Antecedência dos lembretes"] = "Reminder notice", ["À hora de início"] = "At start time",
        ["5 minutos antes"] = "5 minutes before", ["10 minutos antes"] = "10 minutes before",
        ["15 minutos antes"] = "15 minutes before", ["30 minutos antes"] = "30 minutes before",
        ["Só pode criar lembretes para programas que ainda não começaram."] = "Reminders can only be created for programmes that have not started.",
        ["Permita as notificações para receber lembretes de programas."] = "Allow notifications to receive programme reminders.",
        ["Gravações DVR"] = "DVR recordings", ["A carregar gravações…"] = "Loading recordings…",
        ["Gravações recorrentes"] = "Recurring recordings", ["Gerir gravações recorrentes"] = "Manage recurring recordings", ["Gravar série"] = "Record series",
        ["A carregar regras…"] = "Loading rules…", ["Não existem regras de gravação neste perfil."] = "There are no recording rules in this profile.",
        ["Regra ativa"] = "Active rule", ["Editar regra"] = "Edit rule", ["Eliminar regra"] = "Delete rule",
        ["Os agendamentos já criados serão preservados. Eliminar esta regra?"] = "Existing schedules will be preserved. Delete this rule?",
        ["+ Nova regra"] = "+ New rule", ["Procurar episódios"] = "Find episodes", ["Abra uma lista para gerir gravações recorrentes."] = "Open a playlist to manage recurring recordings.",
        ["{0} regras · Perfil {1}"] = "{0} rules · Profile {1}", ["A procurar episódios no guia…"] = "Searching the guide for episodes…", ["{0} novos agendamentos criados."] = "{0} new schedules created.",
        ["Todos os canais"] = "All channels", ["Canal selecionado"] = "Selected channel", ["qualquer horário"] = "any time", ["por volta das {0}"] = "around {0}", ["Título contém"] = "Title contains",
        ["Nome da regra"] = "Rule name", ["Texto presente no título do programa"] = "Text contained in the programme title", ["Tolerância do horário"] = "Time tolerance",
        ["Nova gravação recorrente"] = "New recurring recording", ["Editar gravação recorrente"] = "Edit recurring recording", ["Gravação recorrente"] = "Recurring recording",
        ["A aplicação procura este título no guia e agenda automaticamente novos episódios sem repetir os já identificados."] = "The app searches the guide for this title and automatically schedules new episodes without repeating identified episodes.",
        ["Nome"] = "Name", ["Limitar por horário"] = "Limit by time", ["± {0} minutos"] = "± {0} minutes", ["Guardar regra e procurar episódios"] = "Save rule and find episodes",
        ["Indique o título a procurar no guia."] = "Enter the title to search for in the guide.", ["A regra foi guardada, mas o guia ainda não pôde ser consultado."] = "The rule was saved, but the guide could not yet be checked.",
        ["Não existem gravações neste perfil."] = "There are no recordings in this profile.",
        ["Abrir pasta das gravações"] = "Open recordings folder", ["Escolher outra pasta"] = "Choose another folder",
        ["Pasta das gravações"] = "Recordings folder", ["Pare as gravações em curso antes de alterar a pasta."] = "Stop current recordings before changing the folder.",
        ["A pasta escolhida já contém um ficheiro com o mesmo nome de uma gravação."] = "The selected folder already contains a file with the same name as a recording.",
        ["Gestor de armazenamento"] = "Storage manager", ["A calcular utilização…"] = "Calculating usage…",
        ["Armazenamento do dispositivo"] = "Device storage", ["Cache da aplicação"] = "App cache",
        ["Ficheiros temporários"] = "Temporary files", ["{0} utilizados pela aplicação"] = "{0} used by the app",
        ["{0} livres de {1}"] = "{0} free of {1}", ["Informação de espaço livre indisponível."] = "Free space information is unavailable.",
        ["{0} · {1} ficheiros"] = "{0} · {1} files", ["Gerir gravações"] = "Manage recordings",
        ["Gerir downloads"] = "Manage downloads", ["Eliminar todas"] = "Delete all", ["Eliminar todos"] = "Delete all",
        ["Limpar cache"] = "Clear cache", ["Eliminar todas as gravações"] = "Delete all recordings",
        ["Eliminar todos os downloads"] = "Delete all downloads",
        ["Os valores incluem todas as listas e perfis. Ficheiros temporários em utilização são preservados."] = "Values include all playlists and profiles. Temporary files in use are preserved.",
        ["Eliminar o guia, catálogos e imagens guardados em cache? Serão descarregados novamente quando necessário."] = "Delete cached guide, catalogues and images? They will be downloaded again when needed.",
        ["Eliminar todas as gravações e agendamentos de todas as listas e perfis? As regras recorrentes serão preservadas."] = "Delete all recordings and schedules from every playlist and profile? Recurring rules will be preserved.",
        ["Eliminar todos os downloads offline de todas as listas e perfis?"] = "Delete all offline downloads from every playlist and profile?",
        ["Pare as gravações em curso antes de eliminar todas as gravações."] = "Stop current recordings before deleting all recordings.",
        ["Pause os downloads em curso antes de eliminar todos os downloads."] = "Pause current downloads before deleting all downloads.",
        ["Reproduzir gravação"] = "Play recording", ["Parar gravação"] = "Stop recording",
        ["Eliminar gravação"] = "Delete recording", ["Eliminar este agendamento e o respetivo ficheiro?"] = "Delete this schedule and its file?",
        ["{0} gravações · Perfil {1}"] = "{0} recordings · Profile {1}",
        ["Agendada"] = "Scheduled", ["A gravar"] = "Recording", ["Concluída"] = "Completed", ["Falhou"] = "Failed",
        ["Agendar gravação"] = "Schedule recording", ["Cancelar gravação"] = "Cancel recording", ["Gravar agora"] = "Record now",
        ["Alternar lembrete"] = "Toggle reminder", ["Alternar gravação DVR"] = "Toggle DVR recording",
        ["Gravação agendada"] = "Recording scheduled", ["Gravação cancelada"] = "Recording cancelled",
        ["Gravar canal"] = "Record channel", ["Duração da gravação"] = "Recording duration",
        ["60 minutos"] = "60 minutes", ["120 minutos"] = "120 minutes",
        ["Gravação iniciada"] = "Recording started",
        ["A gravação continua em segundo plano. Pode geri-la em Gravações DVR."] = "Recording continues in the background. You can manage it in DVR recordings.",
        ["O ficheiro desta gravação já não existe."] = "This recording file no longer exists.",
        ["Este programa já terminou e não pode ser gravado."] = "This programme has ended and cannot be recorded.",
        ["Só é possível gravar canais em direto."] = "Only live channels can be recorded.",
        ["Ver programa"] = "Watch programme", ["{0} programas · {1} disponíveis em catch-up · Horário local do dispositivo"] = "{0} programmes · {1} available on catch-up · Device local time",
        ["Vista dos canais"] = "Channel view", ["Simples"] = "Simple", ["Guia TV em grelha"] = "Grid TV guide", ["Vista simples"] = "Simple view",
        ["A carregar canais memorizados…"] = "Loading saved channels…",
        ["Canal"] = "Channel", ["A carregar…"] = "Loading…", ["Sem informação"] = "No information",
        ["AGORA"] = "NOW", ["REVER"] = "WATCH AGAIN",
        ["Pesquisa global"] = "Global search", ["Pesquisar em canais, programas, filmes e séries"] = "Search channels, programmes, movies and series",
        ["A preparar pesquisa global…"] = "Preparing global search…", ["A carregar todos os catálogos…"] = "Loading all catalogues…",
        ["Catálogos prontos · A carregar programação EPG…"] = "Catalogues ready · Loading EPG…",
        ["Escreva pelo menos dois caracteres para pesquisar."] = "Type at least two characters to search.",
        ["Nenhum resultado encontrado."] = "No results found.", ["Não foi possível preparar a pesquisa global."] = "Could not prepare global search.",
        ["Filme"] = "Movie", ["Série"] = "Series", ["Episódio"] = "Episode", ["Programa"] = "Programme",
        ["Pesquisa pronta · {0} conteúdos e {1} programas"] = "Search ready · {0} items and {1} programmes",
        ["Pesquisa pronta · {0} conteúdos · EPG indisponível"] = "Search ready · {0} items · EPG unavailable",
        ["A carregar dados disponíveis…"] = "Loading available data…", ["A carregar {0}…"] = "Loading {0}…",
        ["canais"] = "channels", ["filmes"] = "movies", ["séries"] = "series", ["{0} conteúdos disponíveis · Um dos catálogos não foi carregado."] = "{0} items available · One catalogue could not be loaded.", ["Não foi possível carregar filmes e séries. Use ↻ para tentar novamente."] = "Movies and series could not be loaded. Use ↻ to try again.",
        ["Pesquisa disponível · {0} conteúdos · Algumas fontes não responderam"] = "Search available · {0} items · Some sources did not respond",
        ["Pesquisa pronta · {0} conteúdos e {1} programas · Resultado parcial"] = "Search ready · {0} items and {1} programmes · Partial result",
        ["Pesquisa disponível · {0} conteúdos · O fornecedor demorou demasiado tempo"] = "Search available · {0} items · The provider took too long",
        ["Pesquisa disponível · {0} conteúdos · Resultado parcial"] = "Search available · {0} items · Partial result",
        ["Não foi possível carregar conteúdos. Feche e tente novamente."] = "Could not load content. Close and try again.",
        ["A carregar detalhes…"] = "Loading details…", ["Ver episódios"] = "View episodes", ["Reproduzir"] = "Play",
        ["Ver trailer"] = "Watch trailer", ["Trailer"] = "Trailer", ["Não foi possível abrir o trailer."] = "Could not open the trailer.",
        ["Sinopse"] = "Synopsis", ["Elenco"] = "Cast", ["Realização"] = "Director",
        ["Sem sinopse disponível."] = "No synopsis available.", ["Sem informação disponível."] = "No information available.",
        ["Não foi possível obter informação adicional. A reprodução continua disponível."] = "Could not load additional information. Playback is still available.",
        ["{0} episódios disponíveis"] = "{0} episodes available",
        ["Escolher categoria"] = "Choose category", ["Pesquisar categorias"] = "Search categories", ["Nenhuma categoria encontrada."] = "No category found.",
        ["PSiptv no automóvel"] = "PSiptv in the car", ["Escolher lista"] = "Choose playlist", ["Atualizar canais"] = "Refresh channels",
        ["Escolha uma categoria para ver os canais."] = "Choose a category to see its channels.", ["Escolha uma categoria ou atualize a lista de canais."] = "Choose a category or refresh the channel list.",
        ["Adicione primeiro uma lista quando o automóvel estiver estacionado."] = "Add a playlist first while the vehicle is parked.", ["Não existem listas guardadas."] = "There are no saved playlists.",
        ["Atualize a lista de canais antes de escolher uma categoria."] = "Refresh the channel list before choosing a category.", ["A carregar canais…"] = "Loading channels…",
        ["O fornecedor demorou demasiado tempo. Tente novamente."] = "The provider took too long. Try again.", ["Não foi possível carregar os canais."] = "The channels could not be loaded.",
        ["Atualize a lista de canais e escolha uma categoria."] = "Refresh the channel list and choose a category.", ["Escolha uma lista."] = "Choose a playlist.",
        ["Abra uma lista ou adicione uma conta para começar."] = "Open a playlist or add an account to get started.",
        ["Adicione uma conta Xtream ou uma lista M3U para começar."] = "Add an Xtream account or M3U playlist to get started.",
        ["Escolha um canal para reproduzir"] = "Choose a channel to play", ["Nenhum canal neste grupo."] = "No channels in this group.",
        ["Nenhum conteúdo nesta categoria."] = "No content in this category.", ["A ligar à transmissão…"] = "Connecting to stream…",
        ["A abrir stream…"] = "Opening stream…", ["A receber dados da transmissão…"] = "Receiving stream data…",
        ["O leitor indicou um erro no stream."] = "The player reported a stream error.",
        ["A transmissão ficou sem receber dados."] = "The stream stopped receiving data.",
        ["O leitor não conseguiu abrir a transmissão."] = "The player could not open the stream.",
        ["{0} Nova tentativa {1} de {2} em {3} s…"] = "{0} Retry {1} of {2} in {3} s…",
        ["A restabelecer transmissão · tentativa {0} de {1}…"] = "Restoring stream · attempt {0} of {1}…",
        ["Falha do stream após {0} tentativas · {1}"] = "Stream failed after {0} attempts · {1}",
        ["Falha do stream após {0} tentativas · O leitor não conseguiu abrir a transmissão."] = "Stream failed after {0} attempts · The player could not open the stream.",
        ["A carregar conteúdos…"] = "Loading content…", ["A carregar episódios…"] = "Loading episodes…", ["A carregar programação…"] = "Loading TV guide…",
        ["Use ↻ para carregar os conteúdos."] = "Use ↻ to load content.", ["Use «Atualizar episódios» para carregar os episódios."] = "Use Refresh episodes to load the episodes.",
        ["Use «Atualizar guia» para carregar a programação."] = "Use Refresh guide to load the schedule.",
        ["Voltar a tentar"] = "Retry", ["Abrir com leitor externo"] = "Open with external player", ["Partilhar ecrã"] = "Cast screen", ["Ecrã inteiro"] = "Fullscreen",
        ["Proporção"] = "Aspect ratio", ["Legendas"] = "Subtitles", ["Proporção do ecrã"] = "Screen aspect ratio", ["Ajustar"] = "Fit", ["Preencher ecrã"] = "Fill screen", ["Esticar ao ecrã"] = "Stretch to screen",
        ["Cancelar próximo episódio"] = "Cancel next episode", ["Atualizar episódios"] = "Refresh episodes", ["Atualizar guia"] = "Refresh guide", ["Ver canal em direto"] = "Watch channel live",
        ["À sua maneira"] = "Make it yours", ["Tema"] = "Theme", ["As Suas Listas"] = "Your playlists", ["Personalize a aplicação e controle o acesso às suas listas."] = "Customize the app and control access to your playlists.",
        ["Aparência"] = "Appearance", ["Perfil de cores"] = "Color theme", ["Cor de destaque"] = "Accent color", ["Escuro"] = "Dark", ["Claro"] = "Light", ["Do sistema"] = "System",
        ["Menta"] = "Mint", ["Azul"] = "Blue", ["Violeta"] = "Violet", ["Coral"] = "Coral", ["Âmbar"] = "Amber", ["Reprodução"] = "Playback", ["Preferir leitor externo"] = "Prefer external player",
        ["Escolher leitor"] = "Choose player", ["Leitor selecionado"] = "Selected player", ["Nenhum leitor selecionado"] = "No player selected",
        ["Arranque e segurança"] = "Startup and security", ["Abrir a última lista ao iniciar"] = "Open last playlist at startup", ["As suas listas"] = "Your playlists",
        ["+ Adicionar lista"] = "+ Add playlist", ["Adicionar lista"] = "Add playlist", ["Abrir lista"] = "Open playlist", ["Trocar Playlist"] = "Switch playlist",
        ["Atualizar Conteúdo"] = "Refresh content", ["Editar ligação / PIN"] = "Edit connection / PIN", ["Eliminar lista"] = "Delete playlist", ["Ainda não adicionou nenhuma lista."] = "No playlists added yet.",
        ["Desbloquear lista"] = "Unlock playlist", ["Lista protegida"] = "Protected playlist", ["Desbloquear com PIN"] = "Unlock with PIN", ["Impressão digital / Face ID"] = "Fingerprint / Face ID",
        ["Permitir biometria neste dispositivo"] = "Allow biometrics on this device", ["Cancelar"] = "Cancel", ["Guardar"] = "Save", ["Repetir PIN"] = "Repeat PIN",
        ["Novo PIN parental"] = "New parental PIN", ["PIN de 4 a 8 algarismos"] = "4 to 8 digit PIN", ["Limpar histórico"] = "Clear history", ["Ainda não viu nenhum conteúdo."] = "No watch history yet.",
        ["Organizar categorias"] = "Organize categories", ["Categorias personalizadas"] = "Custom categories", ["+ Adicionar categoria"] = "+ Add category", ["Editar categoria"] = "Edit category",
        ["Nome da categoria"] = "Category name", ["Eliminar categoria"] = "Delete category", ["Nome da lista"] = "Playlist name", ["Utilizador"] = "Username", ["Palavra-passe"] = "Password"
        ,
        ["Tipo de conta"] = "Account type", ["Editar lista"] = "Edit playlist", ["Gerir esta lista"] = "Manage this playlist", ["Guia TV · XMLTV"] = "TV guide · XMLTV",
        ["Ficheiro M3U local"] = "Local M3U file", ["Escolher ficheiro M3U"] = "Choose M3U file", ["Endereço MAC"] = "MAC address", ["Token de acesso"] = "Access token",
        ["Escolha um ficheiro .m3u ou .m3u8"] = "Choose a .m3u or .m3u8 file", ["Escolha um ficheiro .m3u ou .m3u8."] = "Choose a .m3u or .m3u8 file.", ["Escolha um ficheiro M3U local."] = "Choose a local M3U file.",
        ["O ficheiro M3U local não foi encontrado."] = "The local M3U file was not found.",
        ["https://fornecedor.pt:porta"] = "https://provider.example:port", ["https://fornecedor.pt/lista.m3u"] = "https://provider.example/playlist.m3u",
        ["https://fornecedor.pt/guia.xml (opcional)"] = "https://provider.example/guide.xml (optional)", ["+ Adicionar fonte"] = "+ Add source",
        ["Remover PIN atual"] = "Remove current PIN", ["Deixe vazio para manter o PIN atual."] = "Leave blank to keep the current PIN.",
        ["Dê um nome à lista."] = "Give the playlist a name.", ["Preencha o utilizador e a palavra-passe Xtream."] = "Enter the Xtream username and password.",
        ["Introduza o endereço MAC do dispositivo Stalker."] = "Enter the Stalker device MAC address.", ["Introduza o token de acesso do servidor."] = "Enter the server access token.",
        ["No Xtream, indique apenas o endereço base do servidor, sem player_api.php nem parâmetros."] = "For Xtream, enter only the server base URL, without player_api.php or parameters.",
        ["Os PINs não coincidem."] = "The PINs do not match.", ["Escolha entre remover o PIN atual ou definir um novo."] = "Choose either to remove the current PIN or set a new one.",
        ["A verificar a ligação…"] = "Checking the connection…", ["Protegida com PIN"] = "PIN protected", ["Sem PIN"] = "No PIN",
        ["A fonte predefinida abre automaticamente ao entrar na tab Browser."] = "The default source opens automatically when you enter the Browser tab.",
        ["Ainda não existem fontes. Adicione um endereço para utilizar o browser."] = "There are no sources yet. Add an address to use the browser.",
        ["Nome apresentado na lista"] = "Name shown in the list", ["Endereço HTTP ou HTTPS"] = "HTTP or HTTPS address", ["Remover fonte"] = "Remove source",
        ["Introduza um nome para a fonte."] = "Enter a name for the source.", ["Avançar"] = "Forward", ["Atualizar página"] = "Refresh page",
        ["Sem fontes"] = "No sources", ["Adicione um endereço nas configurações da aplicação."] = "Add an address in the app settings.",
        ["Abrir num browser externo"] = "Open in an external browser", ["Adicione uma fonte nas configurações."] = "Add a source in settings.",
        ["Abrir endereço"] = "Open address", ["Endereço inválido"] = "Invalid address",
        ["Reproduzir stream no leitor"] = "Play stream in the video player",
        ["Abrir com"] = "Open with", ["Abrir com…"] = "Open with…", ["Não foi encontrado nenhum browser instalado."] = "No installed browser was found.",
        ["Eliminar"] = "Delete", ["Remover"] = "Remove", ["Editar"] = "Edit", ["Predefinida"] = "Default",
        ["Definir como predefinida"] = "Set as default", ["Eliminar esta categoria personalizada? Os conteúdos do fornecedor são preservados."] = "Delete this custom category? Provider content will be preserved.",
        ["Escolha um nome único com 1 a 80 caracteres."] = "Choose a unique name between 1 and 80 characters.",
        ["Pedido cancelado ou sem resposta. Tente atualizar."] = "The request was cancelled or received no response. Try refreshing.",
        ["Não foi possível obter os episódios."] = "The episodes could not be retrieved.", ["Não foi possível obter o guia TV."] = "The TV guide could not be retrieved.",
        ["Leitor externo"] = "External player", ["Leitor externo indisponível"] = "External player unavailable", ["Escolher leitor de vídeo"] = "Choose video player",
        ["Não foi encontrado nenhum leitor de vídeo compatível."] = "No compatible video player was found.",
        ["A escolha de uma aplicação específica está disponível no Android."] = "Choosing a specific app is available on Android.",
        ["Não foi possível abrir um leitor externo. Reproduzir no leitor integrado?"] = "An external player could not be opened. Play in the integrated player?", ["Reproduzir"] = "Play",
        ["Não foi possível abrir o seletor de leitores."] = "The player chooser could not be opened.", ["Não foi possível consultar os leitores instalados."] = "Installed players could not be queried.",
        ["Instale um leitor de vídeo compatível, como VLC ou MX Player."] = "Install a compatible video player, such as VLC or MX Player.",
        ["Selecione um leitor que suporte listas M3U, como VLC."] = "Choose a player that supports M3U playlists, such as VLC.",
        ["Instale o VLC para abrir este vídeo externamente no iPhone ou iPad."] = "Install VLC to open this video externally on iPhone or iPad.",
        ["O VLC deixou de estar disponível. Escolha novamente o leitor externo nas configurações."] = "VLC is no longer available. Choose the external player again in settings.",
        ["Selecione uma aplicação que suporte listas M3U, como VLC."] = "Choose an app that supports M3U playlists, such as VLC.",
        ["Associe os ficheiros M3U a um leitor como VLC."] = "Associate M3U files with a player such as VLC.",
        ["Guardar nos favoritos"] = "Add to favourites", ["Remover dos favoritos"] = "Remove from favourites", ["Pesquisar favoritos"] = "Search favourites", ["Séries e episódios"] = "Series and episodes", ["Todos"] = "All", ["Canais"] = "Channels", ["★ Favoritos"] = "★ Favourites",
        ["Sem favoritos para mostrar. Use ☆ junto a um conteúdo para o guardar."] = "No favourites to show. Use ☆ next to content to save it.",
        ["Sem programação disponível para este canal."] = "No schedule is available for this channel.", ["EM DIRETO"] = "LIVE",
        ["Não foi possível reproduzir. Toque novamente no canal para tentar."] = "Playback failed. Tap the channel again to retry.",
        ["Maximizar ecrã"] = "Enter fullscreen", ["Sair do ecrã inteiro"] = "Exit fullscreen", ["Abrir canais da categoria"] = "Open channels in this category", ["Fechar canais"] = "Close channels",
        ["O fornecedor demorou demasiado tempo. Use ↻ para tentar novamente."] = "The provider took too long. Use ↻ to try again.",
        ["Não foi possível carregar. Use ↻ para tentar novamente."] = "Loading failed. Use ↻ to try again.",
        ["O canal já não pertence à lista visível."] = "The channel is no longer in the visible list.", ["A reprodução precisa de autorização no dispositivo."] = "Playback requires authorization on the device.",
        ["Demasiadas tentativas. Aguarde 30 segundos."] = "Too many attempts. Wait 30 seconds.", ["Pode tentar novamente ou introduzir o PIN."] = "You can try again or enter the PIN.", ["Usar PIN"] = "Use PIN",
        ["Confirme a sua identidade no dispositivo"] = "Confirm your identity on the device", ["Desbloquear a sua lista PSiptv"] = "Unlock your PSiptv playlist",
        ["Reproduzir ou pausar"] = "Play or pause", ["Pausar"] = "Pause", ["Escolher faixa de legendas"] = "Choose subtitle track",
        ["Ative a faixa de legendas nas configurações e reabra o vídeo."] = "Enable subtitles in settings and reopen the video.",
        ["Este vídeo não contém faixas de legendas."] = "This video has no subtitle tracks.",
        ["Não foi possível reproduzir. Verifique a ligação ou tente outro descodificador nas configurações."] = "Playback failed. Check the connection or try another decoder in settings.",
        ["Ligação expirada. Procure novamente o dispositivo."] = "The connection expired. Search for the device again.", ["O controlo remoto não está disponível."] = "Remote control is unavailable.", ["Telemóvel"] = "Phone",
        ["Transmitir"] = "Cast", ["Transmitir ecrã (nativo)"] = "Cast screen (native)", ["Bloqueador de publicidade e popups ativo"] = "Ad and popup blocker active",
        ["Abra as definições rápidas do dispositivo e escolha Transmitir, Smart View ou Partilha de ecrã."] = "Open the device quick settings and choose Cast, Smart View or Screen sharing.",
        ["Prima Windows + K e escolha o ecrã sem fios."] = "Press Windows + K and choose the wireless display.",
        ["Abra a Central de controlo e escolha Duplicar ecrã para ligar a um dispositivo AirPlay."] = "Open Control Centre and choose Screen Mirroring to connect to an AirPlay device.",
        ["O dispositivo Chromecast já está ligado."] = "The Chromecast device is already connected.",
        ["Não foi encontrado nenhum Chromecast. Confirme que está ligado e na mesma rede Wi-Fi."] = "No Chromecast was found. Make sure it is powered on and on the same Wi-Fi network.",
        ["Não foi possível iniciar o Chromecast. Confirme que o Google Play Services está atualizado e que ambos os dispositivos estão na mesma rede Wi-Fi."] = "Chromecast could not be started. Make sure Google Play Services is up to date and both devices are on the same Wi-Fi network.",
        ["A ligação direta ao Chromecast está disponível na versão Android."] = "Direct Chromecast connection is available on Android.",
        ["Chromecast ligado. Abra um canal para o transmitir."] = "Chromecast connected. Open a channel to cast it.",
        ["Sem fonte predefinida"] = "No default source", ["Abra uma lista"] = "Open a playlist", ["conteúdos"] = "items", ["Cache"] = "Cache", ["selecionado"] = "selected", ["Voltar"] = "Back",
        ["Cache do guia e imagens limpo. As listas e os favoritos foram preservados."] = "Guide and image cache cleared. Playlists and favourites were preserved.",
        ["Descodificador, buffer, legendas, velocidade, OpenSL ES e OpenGL estão disponíveis no leitor integrado Android."] = "Decoder, buffer, subtitles, speed, OpenSL ES and OpenGL are available in the integrated Android player.",
        ["indisponível neste dispositivo"] = "unavailable on this device", ["Introduza um agente válido sem quebras de linha."] = "Enter a valid user agent without line breaks.",
        ["A interface será atualizada ao reabrir a aplicação. / The interface will update when you reopen the app."] = "The interface will update when you reopen the app.",
        ["Abre os conteúdos num leitor instalado e envia-lhe o endereço do vídeo."] = "Opens content in an installed player and sends it the video URL.",
        ["Escolha a aplicação que recebe diretamente o endereço do vídeo."] = "Choose the app that receives the video URL directly.",
        ["O Windows apresenta o seletor de aplicações sempre que abrir um conteúdo externo."] = "Windows shows the app picker whenever you open external content.",
        ["Use o seletor do iOS ou abra diretamente no VLC, quando estiver instalado."] = "Use the iOS app picker or open directly in VLC when it is installed.",
        ["O macOS abre uma lista M3U na aplicação associada a este tipo de ficheiro."] = "macOS opens an M3U playlist in the app associated with this file type.",
        ["O sistema abre uma lista M3U numa aplicação compatível."] = "The system opens an M3U playlist in a compatible app.",
        ["Seletor de aplicações do Windows"] = "Windows app picker", ["Seletor de aplicações do iOS"] = "iOS app picker",
        ["Aplicação predefinida do macOS"] = "Default macOS app", ["Aplicação predefinida do sistema"] = "Default system app",
        ["As listas protegidas continuam a pedir PIN ou biometria."] = "Protected playlists still require a PIN or biometrics.",
        ["Não foi possível contactar o fornecedor. Verifique o endereço e a ligação à Internet."] = "The provider could not be reached. Check the address and your Internet connection.",
        ["O fornecedor demorou demasiado tempo a responder. Tente novamente."] = "The provider took too long to respond. Try again.",
        ["O fornecedor devolveu uma resposta inválida."] = "The provider returned an invalid response.", ["O guia TV devolvido não é XML válido."] = "The returned TV guide is not valid XML.",
        ["Não foi possível concluir a operação. Verifique os dados e tente novamente."] = "The operation could not be completed. Check the details and try again.",
        ["Esta lista não tem fonte EPG. Adicione um endereço XMLTV nas configurações."] = "This playlist has no EPG source. Add an XMLTV URL in settings.",
        ["Este canal não tem tvg-id para associar ao guia XMLTV."] = "This channel has no tvg-id to match with the XMLTV guide.",
        ["Não foi possível ler as listas guardadas."] = "Saved playlists could not be read.", ["A versão dos dados das listas não é suportada."] = "The playlist data version is not supported.",
        ["A chave de encriptação das listas não está disponível."] = "The playlist encryption key is unavailable.", ["A chave de encriptação das listas é inválida."] = "The playlist encryption key is invalid.",
        ["Os PINs devem coincidir e ter 4 a 8 algarismos."] = "The PINs must match and contain 4 to 8 digits.",
        ["PSiptv é um leitor de listas fornecidas pelo utilizador. Não inclui nem vende canais, filmes ou séries.\n\nUtilize apenas conteúdos a que tenha acesso autorizado e respeite as condições do seu fornecedor. A disponibilidade, qualidade e permissões de transmissão dependem desse fornecedor.\n\nAo abrir um leitor externo, o endereço da transmissão é enviado à aplicação escolhida. A partilha de ecrã pode mostrar informação visível no dispositivo.\n\nVersão instalada: {0}"] = "PSiptv is a player for user-provided playlists. It does not include or sell channels, movies or series.\n\nOnly use content you are authorized to access and respect your provider's terms. Availability, quality and streaming permissions depend on that provider.\n\nWhen you open an external player, the stream URL is sent to the chosen app. Screen sharing may display information visible on the device.\n\nInstalled version: {0}",
        ["As listas, credenciais, preferências por lista e histórico são guardados no armazenamento seguro local do dispositivo. As preferências gerais são guardadas localmente. O guia EPG é guardado localmente em cache para permitir uma abertura rápida e atualizações em segundo plano.\n\nA aplicação contacta os endereços do fornecedor, do guia XMLTV e das imagens da lista para apresentar e reproduzir os conteúdos. Esses serviços recebem o endereço IP e o agente do utilizador configurado.\n\nA biometria é verificada pelo sistema operativo. A aplicação não recebe nem guarda impressões digitais ou imagens faciais. O PIN é guardado como hash com salt.\n\nPode limpar o histórico e eliminar listas nas configurações. Eliminar uma lista remove também o respetivo histórico, favoritos, personalizações e cache EPG. A aplicação não inclui um serviço próprio de recolha de telemetria."] = "Playlists, credentials, per-playlist preferences and history are stored in secure local device storage. General preferences are stored locally. The EPG guide is cached locally for fast opening and background updates.\n\nThe app contacts the provider, XMLTV guide and playlist image addresses to display and play content. Those services receive the IP address and configured user agent.\n\nBiometrics are verified by the operating system. The app does not receive or store fingerprints or facial images. The PIN is stored as a salted hash.\n\nYou can clear history and delete playlists in settings. Deleting a playlist also removes its history, favourites, customizations and EPG cache. The app does not include its own telemetry collection service.",
        ["Os dados protegidos têm um formato inválido."] = "Protected data has an invalid format.", ["Não foi possível desencriptar os dados protegidos."] = "Protected data could not be decrypted.",
        ["Os dados protegidos da lista têm um formato inválido."] = "Protected playlist data has an invalid format.", ["Não foi possível desencriptar os dados da lista."] = "Playlist data could not be decrypted.",
        ["A fonte não contém um guia XMLTV válido."] = "The source does not contain a valid XMLTV guide.", ["Sem título"] = "Untitled", ["Sem categoria"] = "Uncategorized",
        ["A resposta excede o limite de 40 MB."] = "The response exceeds the 40 MB limit.", ["A conta Xtream foi recusada. Verifique o utilizador e a palavra-passe."] = "The Xtream account was rejected. Check the username and password.",
        ["A conta Xtream não está ativa. Contacte o fornecedor."] = "The Xtream account is not active. Contact the provider.", ["Não foi possível ler os favoritos guardados."] = "Saved favourites could not be read.",
        ["Introduza um endereço HTTP ou HTTPS válido."] = "Enter a valid HTTP or HTTPS address.", ["O endereço não devolveu uma lista M3U válida (#EXTM3U)."] = "The address did not return a valid M3U playlist (#EXTM3U).",
        ["A lista não contém conteúdos HTTP/HTTPS reproduzíveis."] = "The playlist contains no playable HTTP/HTTPS content.", ["A lista não contém conteúdos reproduzíveis."] = "The playlist contains no playable content.",
        ["A fonte não devolveu canais reproduzíveis."] = "The source returned no playable channels.", ["A fonte não devolveu conteúdos reproduzíveis."] = "The source returned no playable content.",
        ["O portal Stalker não devolveu um token válido."] = "The Stalker portal did not return a valid token.", ["O portal Stalker não devolveu uma transmissão HTTP válida."] = "The Stalker portal did not return a valid HTTP stream.",
        ["A resposta da fonte excede o limite de 120 MB."] = "The source response exceeds the 120 MB limit.", ["O PIN deve ter entre 4 e 8 algarismos."] = "The PIN must contain 4 to 8 digits."
    };
}
